### ISSUE TITLE
Error on duplicates_handling == "comb"

### ISSUE THREAD

**Issue by coverton-usgs** [movestore/movebank-download#2]
I believe I have the description correct.  When changing the default error handling on Moveapps I receive the error 

> " Error in .local(x, ...): Not all move object in the list have the same timezone in the timestamp "  

But looking at the logs I see that the individuals are not recognized as having GPS sensors either 

> 2021-04-10 00:06:19.919 [Thread-5] INFO  o.m.m.copilot.v1.ProcessLogger - (APP) Error in .local(study, sensorID, animalName, login, ...): Sensor(s): 'GPS' is/are not available for this study

My archaic local code for downloading from movebank encountered the same timezone error.
I was using loops and I had to set the timezone to UTC upon combining loops.
```
iterations<-ceiling(nrow(animals1)/300)
for (i in 1:iterations){
  animalset<-animals1[(1+300*(i-1)):min(300*i,nrow(animals1)),]
  try1<-getMovebankData(study = mbstudy, login= mblogin, animalName=c(animalset$individual_id), removeDuplicatedTimestamps=TRUE,includeExtraSensors=TRUE)
  if(i==1){allmovebankdata<-try1} else {allmovebankdata<-moveStack(allmovebankdata,try1)}
  tz(allmovebankdata@timestamps)<-"UTC"
}
```

I'm not sure how'd you get around this with the do.call functions (presumably line 83).  Or if its even needed there given the other issue.  

The only other thing that jumps at me is 2 arguments are not created when using duplicates_handling=="comb"
` arguments[["includeExtraSensors"]] = FALSE`
 and 
`arguments[["deploymentAsIndividuals"]] = FALSE`
only exist within duplicates_handling=="first" but I can't image how those would result in this error.

The code works as expected with duplicates_handling=="first"

**Comment by andreakoelzsch** [comment]
Hi Cory, sorry that I didnt see this issue at the time, I am just starting to become more familiar with GitHub. The error about the timezones is caused by conversion of a list of move objects including a NULL object to a movestack. MoveApps Apps need as input and output (as of now) movestack objects. This App has developed quite a bit since this issue and this error should not appear any more. I have fixed it by checking and taking out any NULL elements from the list before making a movestack at the end of the App. Hope this is helpful for you. Best, Andrea
