### ISSUE TITLE
require at least 1 sensor selection

### ISSUE THREAD

**Issue by sarahcd** [movestore/movebank-download#4]
I was able to uncheck all sensors and proceed with saving the app. Running the workflow leads to no data accessed an an error:
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘moveStack’ for signature ‘"NULL"’

**Comment by andreakoelzsch** [comment]
Hi Sarah, yes, we are aware of this possibility to allow users to do non-sensible things. This implementation was the most straight forward with the limited funding we have at present. We have taken care to give the NULL back as error and give the message "The output of this App contains no locations/events. The analysis result is null. Note that a subsequent App will run into an error, because null input is not allowed." in the cargo agent ("i" button is a nice wording for that, thanks), so that people see that no data have been uploaded. You have also added move details to the readme about this, have you? I will check and if not add something. That will have to suffice for now, sorry. With move2 this App will have to be adapted anyway, so I can try to make this error message a bit more specific. OK?
